export const filtersDataForUi = [
  {
    id: 1,
    label: 'Note client',
    name: 'clientNoteMin',
    min: 0,
    max: 5,
    step: 1,
    unit: '⭐️',
    value: 0,
    isFilterChecked: false,
  },
  {
    id: 2,
    label: 'Distance maximale de ramassage',
    name: 'pickupDistanceMax',
    min: 0,
    max: 2000,
    step: 100,
    unit: 'm',
    value: 800,
    isFilterChecked: true,
  },
  {
    id: 3,
    label: 'Prix minimum de la course',
    name: 'priceMin',
    min: 0,
    max: 200,
    step: 1,
    unit: '€',
    value: 0,
    isFilterChecked: false,
  },
  {
    id: 4,
    label: 'Distance maximale de la course',
    name: 'distanceMax',
    min: 0,
    max: 100,
    step: 5,
    unit: 'km',
    value: 60,
    isFilterChecked: true,
  },
  {
    id: 5,
    label: 'Majoration',
    name: 'markupMin',
    min: 1,
    max: 3,
    step: 0.2,
    unit: '%',
    value: 0,
    isFilterChecked: false,
  },
];
