export const filtersDataForUi = [
  {
    id: 1,
    label: 'Note client',
    name: 'clientNoteMin',
    min: 0,
    max: 5,
    step: 1,
    unit: '*',
  },
  {
    id: 2,
    label: 'Distance maximale de ramassage',
    name: 'pickupDistanceMax',
    min: 0,
    max: 2000,
    step: 100,
    unit: 'm',
  },
  {
    id: 3,
    label: 'Prix minimum de la course',
    name: 'priceMin',
    min: 0,
    max: 200,
    step: 1,
    unit: '€',
  },
  {
    id: 4,
    label: 'Distance maximale de la course',
    name: 'distanceMax',
    min: 0,
    max: 500,
    step: 5,
    unit: 'km',
  },
  {
    id: 5,
    label: 'Majoration',
    name: 'markupMin',
    min: 0,
    max: 100,
    step: 2,
    unit: '%',
  },
];
