export const filtersDataForUi = [
  {
    id: 1,
    label: 'Notation voyageur',
    name: 'clientNoteMin',
    min: 0,
    max: 5,
    step: 1,
    unit: '',
  },
  {
    id: 2,
    label: 'Distance de ramassage',
    name: 'pickupDistanceMax',
    min: 0,
    max: 100000,
    step: 50,
    unit: 'm',
  },
  {
    id: 3,
    label: 'Prix de la course',
    name: 'priceMin',
    min: 0,
    max: 1000,
    step: 5,
    unit: '€',
  },
  {
    id: 4,
    label: 'Distance de la course',
    name: 'distanceMax',
    min: 0,
    max: 100000,
    step: 50,
    unit: 'm',
  },
  {
    id: 5,
    label: 'Majoration',
    name: 'markupMin',
    min: 0,
    max: 100,
    step: 5,
    unit: '%',
  },
];
